version: '3.8'

services:
  db:
    image: postgres:16
    container_name: bemowo_postgres
    environment:
      POSTGRES_DB: bemowo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SecurePassword123
    ports:
      - "5433:5432"
    networks:
      - bemowo-net

  backend:
    build:
      context: .
    container_name: bemowo_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_PASSWORD: SecurePassword123
    networks:
      - bemowo-net

networks:
  bemowo-net:
